= Data Warehouse

== Was ist Data Warehouse?
Große Datenbank die alle Daten von z.B. einer Firma zusammenfasst, um große Analysen für die Zukunft zu berechnen.

* ist kein Backup, weil Daten massiv verändert werden.

== Vortrag

=== Stern-Schema
* Fakten und Dimensionen
** Fakten enthält Detaildaten und erleichtern keine Analysen
** Faktentabellen werden versucht "schlank" zu halten(nur keys usw.)
** Dimensionen definieren Faktentabelle (z.B. Verkauf -> Kunde, Filiale, Zeit). Man kann nach den Dimensionen "filtern"

=== OLAP Anfragen
* verdichten die Daten (Aggregatfunktionen wie sum, count, avg, ...)

=== Roll-up/Drill-down Anfragen
* mehr Attribute in group by = *drill-down*
* weniger Attribute in group by = *roll-up*
* ultimative Verdichtung ist *ohne* group by

=== Flexible Auswertung: slice and dice
* *slice:* einen Teil des verdichteten Datenwürfels rausnehmen um diesen genauer zu analysieren (z.B. nur die Produktgruppe "Haushaltsgeräte")
* *dice:* den slice nochmal genauer zerteilen (alle Waschmaschinen aus der Gruppe "Haushaltsgeräte")

=== cube-Operator
* erstellt verkürzt einen Cube (genau wie fettes "union"-statement)
[source,sql]
----
select p.Hersteller, z.Jahr, f.Land, sum(v.Anzahl)
from Verkäufe v, Produkte p, Zeit z, Filialen f
where v.Produkt = p.ProduktNr and p.Produkttyp = 'Handy' and v.VerkDatum =
    z.Datum and v.Filiale = f.Filialkennung
group by cube (z.Jahr, p.Hersteller, f.Land);
----

